stages:
  - build
  - deploy



# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: maven-repository-cache
  paths:
    - node_modules/


build:
  image: gitlab_local_node:10
  stage: build
  tags:
    - Frontend
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    name: "$CI_JOB_NAME"
    paths:
      - dist



deploy:
  image: alpine
  stage: deploy
  tags:
    - Frontend
  dependencies:
    - build
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - rsync -rav --delete dist/ deploy@47.110.156.186:/home/deploy/www-crrc/